<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="65859" started-at="2020-09-19T08:54:52Z" finished-at="2020-09-19T08:55:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="65859" started-at="2020-09-19T08:54:52Z" finished-at="2020-09-19T08:55:58Z">
      <class name="com.testcases.LoginTest">
        <test-method status="PASS" signature="extentReportSetup()[pri:0, instance:com.testcases.LoginTest@183967b]" name="extentReportSetup" is-config="true" duration-ms="360" started-at="2020-09-19T14:24:52Z" finished-at="2020-09-19T14:24:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportSetup -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testcases.LoginTest@183967b]" name="setUp" is-config="true" duration-ms="17319" started-at="2020-09-19T14:24:53Z" finished-at="2020-09-19T14:25:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test01()[pri:0, instance:com.testcases.LoginTest@183967b]" name="test01" duration-ms="226" started-at="2020-09-19T14:25:10Z" finished-at="2020-09-19T14:25:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginTest@183967b]" name="getResult" is-config="true" duration-ms="791" started-at="2020-09-19T14:25:10Z" finished-at="2020-09-19T14:25:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test01 status=SUCCESS method=LoginTest.test01()[pri:0, instance:com.testcases.LoginTest@183967b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testcases.LoginTest@183967b]" name="setUp" is-config="true" duration-ms="11322" started-at="2020-09-19T14:25:11Z" finished-at="2020-09-19T14:25:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test02()[pri:0, instance:com.testcases.LoginTest@183967b]" name="test02" duration-ms="6607" started-at="2020-09-19T14:25:22Z" finished-at="2020-09-19T14:25:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginTest@183967b]" name="getResult" is-config="true" duration-ms="1027" started-at="2020-09-19T14:25:29Z" finished-at="2020-09-19T14:25:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test02 status=SUCCESS method=LoginTest.test02()[pri:0, instance:com.testcases.LoginTest@183967b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testcases.LoginTest@183967b]" name="setUp" is-config="true" duration-ms="17582" started-at="2020-09-19T14:25:30Z" finished-at="2020-09-19T14:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test03()[pri:0, instance:com.testcases.LoginTest@183967b]" name="test03" duration-ms="7309" started-at="2020-09-19T14:25:48Z" finished-at="2020-09-19T14:25:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JavaByKiran | Log in] but found [JavaByKiran | Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JavaByKiran | Log in] but found [JavaByKiran | Dashboard]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.testcases.LoginTest.test03(LoginTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.testcases.LoginTest@183967b]" name="getResult" is-config="true" duration-ms="1711" started-at="2020-09-19T14:25:55Z" finished-at="2020-09-19T14:25:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test03 status=FAILURE method=LoginTest.test03()[pri:0, instance:com.testcases.LoginTest@183967b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.testcases.LoginTest@183967b]" name="endReport" is-config="true" duration-ms="1553" started-at="2020-09-19T14:25:57Z" finished-at="2020-09-19T14:25:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
